### ISSUE TITLE
Remove redundancy in find teammates page

### ISSUE THREAD

**Issue by chehak123** [Fem-STEM/FemSTEM-Web-App#11]
After selecting few skills for finding teammates, there is redundancy in teammates. 

![Screenshot (317)_LI](https://user-images.githubusercontent.com/53402167/156553685-1cd35b57-cee7-47a3-8fe4-55449e05a661.jpg)
![Screenshot (322)_LI](https://user-images.githubusercontent.com/53402167/156553690-4831c09e-1db4-4ced-9951-417f58637010.jpg)

There should not be repitition in results . Also if there are same teammate under mentee and mentor then also only one should be shown.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by chehak123** [comment]
Assigned @aashay-03
