### ISSUE TITLE
"Home" page: Make the list of blue bullet points look consistent in mobile view

### ISSUE THREAD

**Issue by Swatilekha-Roy** [Fem-STEM/FemSTEM-Web-App#16]
![Screenshot (648)](https://user-images.githubusercontent.com/66589183/156695896-182555fd-fa36-4191-9167-9d1ed1c019c2.png)

Right now, the text looks untidy and inconsistent, please fix that.
- Please make sure you refer to the issue number # when you are making a pull request.
- Please add screenshots and (or) screen recordings for your resolution of the issue in your pull request, in order to ensure your pr gets merged soon. This is highly recommended.

**Comment by NPriyajit** [comment]
I want to work on this

**Comment by Swatilekha-Roy** [comment]
Go ahead, @NPriyajit! All the best.

**Comment by Swatilekha-Roy** [comment]
Hi @NPriyajit I just unassigned you from the issue as you already have 2 open assigned issues, please complete them first. Thanks.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by chehak123** [comment]
Assigned @aashay-03
