### ISSUE TITLE
"Pride" Page": Stop the Big Header image from repeating

### ISSUE THREAD

**Issue by Swatilekha-Roy** [Fem-STEM/FemSTEM-Web-App#17]
![Screenshot (650)](https://user-images.githubusercontent.com/66589183/156696829-e074240f-bd44-4029-91ff-43d57ecaf054.png)

- Please make sure you refer to the issue number # when you are making a pull request.
- Please add screenshots and (or) screen recordings for your resolution of the issue in your pull request, in order to ensure your pr gets merged soon. This is highly recommended.

**Comment by NPriyajit** [comment]
I want to work on this

**Comment by Swatilekha-Roy** [comment]
Go ahead, @NPriyajit! All the best.
