### ISSUE TITLE
Show/hide Password functionality while signing up the page

### ISSUE THREAD

**Issue by Siddhesh777** [Fem-STEM/FemSTEM-Web-App#29]
I would like to add a button which will toggle the visibility of password (show->hide and vice versa)

I am contributor at GSSOC'22.
Please assign this task to me.

![1](https://user-images.githubusercontent.com/77476772/161203256-ec915f26-d5fe-4e96-b088-d840e4098de4.png)

**Comment by chehak123** [comment]
Assigned @Siddhesh777

**Comment by Siddhesh777** [comment]
hey @chehak123 
I will be great if you add GSSOC'22 label 
And also some proper level label .

**Comment by Siddhesh777** [comment]
hey @chehak123 
Can you please review this PR?

**Comment by Siddhesh777** [comment]
hey @Swatilekha-Roy 
Can you please review this PR?
