### ISSUE TITLE
Pride.ejs page: Make the "Read More" and "Read Less" buttons for different cards independent of each other

### ISSUE THREAD

**Issue by Swatilekha-Roy** [Fem-STEM/FemSTEM-Web-App#3]
![Screenshot (614)](https://user-images.githubusercontent.com/66589183/153145606-9b76b48c-f32a-4c89-a0a3-ae858022e5e1.png)
![Screenshot (615)](https://user-images.githubusercontent.com/66589183/153145609-d8d4e41d-1a9a-4c30-afb0-30fa538d4291.png)

Right now, clicking on the button of one card expands both the cards (due to the javascript targeting the same query)- this needs to be fixed for the cards!

**Comment by youganjansarki18** [comment]
**I would like to work on this bug.
Can you please assign it to me :)**
**_(gssoc '22)_**

**Comment by chehak123** [comment]
Assigned @youganjansarki18

**Comment by Swatilekha-Roy** [comment]
Hello @youganjansarki18, it's been more than 5 days, so we are closing this issue now as it got resolved! Please consider taking up another issue and try to complete it on time. All the best!
