### ISSUE TITLE
Confirm password field 

### ISSUE THREAD

**Issue by Siddhesh777** [Fem-STEM/FemSTEM-Web-App#32]
There should be a confirm password field while signing up the page.
If both the password matches then only use should be registered successfully else it should throw an error.

![1](https://user-images.githubusercontent.com/77476772/161424258-e237ba23-c1da-48bf-9c5c-c01a2a7ac5f6.png)

I am contributor at GSSOC'22.
Please assign this issue to me.

**Comment by Siddhesh777** [comment]
@chehak123 
Please assign this to me.

**Comment by Swatilekha-Roy** [comment]
Please go ahead, @Siddhesh777! Assigning you the issue. All the best!

**Comment by Siddhesh777** [comment]
hey @Swatilekha-Roy Please add Label of GSSOC'22
