### ISSUE TITLE
Add CODE_OF_CONDUCT.md and Contribute.md file 

### ISSUE THREAD

**Issue by Sukriti-m** [Fem-STEM/FemSTEM-Web-App#34]
I saw that in this project CODE_OF_CONDUCT.md and Contribute.md file are missing.
I'd like to add these files in the project.
I'd be grateful if you could assign this task to me under GSSoC'22.
@Swatilekha-Roy @chehak123 

PS: the level labels which you are assigning to the issues will not have spaces between them.
It's written as "Level 2" but it should be written as "Level2".

**Comment by Swatilekha-Roy** [comment]
Good catch, @Sukriti-m! Just assigned you the issue. All the best!
P.S.: Thank you so much for pointing out the issue with the labels! Just fixed it.
