### ISSUE TITLE
Segregating  mongo local and remote urls in .env File With a dotEnvExample

### ISSUE THREAD

**Issue by NPriyajit** [Fem-STEM/FemSTEM-Web-App#4]
1> Create a Dot Env Example File for New User, For Better Copy and Paste The Contents.
2> Use 2 ENV variables, LOCAL & REMOTE, for users who do not have a remote account.

**Comment by NPriyajit** [comment]
I want to Work on this, Issue
@GSSOC22

**Comment by Swatilekha-Roy** [comment]
Go ahead, @NPriyajit! All the best.
