### ISSUE TITLE
Buttons are not aligned properly - Improvement

### ISSUE THREAD

**Issue by NPriyajit** [Fem-STEM/FemSTEM-Web-App#5]
![image](https://user-images.githubusercontent.com/47923239/156131890-9aec217f-5b29-41ae-8b64-679ec8362c51.png)

Search Functionality and Add Opportunity Buttons are not aligned Properly

**Comment by NPriyajit** [comment]
I Want to work on this Please!
@GSSOC22

**Comment by chehak123** [comment]
Assigned @NPriyajit
