### ISSUE TITLE
Read More Button under Pride section is not functioning properly

### ISSUE THREAD

**Issue by aashay-03** [Fem-STEM/FemSTEM-Web-App#9]
![ReadMoreBtn](https://user-images.githubusercontent.com/100699709/156503791-3e5de1ac-1952-4239-a4a8-2a3addd9ceef.png)
When the read more button for the rightmost story is clicked it performs the function for the story in the middle and not for the one on the right.

**Comment by aashay-03** [comment]
I want to work on this issue under GSSoC22.

**Comment by chehak123** [comment]
go ahead @aashay-03
